kind: pipeline
name: default

steps:
- name: build
  image: golang
  commands:
    - echo -n "Hello"

steps:
- name: docker  
  image: plugins/docker
  settings:
    repo: arenstar/puppet-knock
    tags: latest
