language: ruby

rvm:
  - 1.8.7
  - 1.9.3
  - 2.0.0

script:
  - 'rake spec'
  
matrix:
  exclude:
    - rvm: 2.0.0
      env: PUPPET_GEM_VERSION="~> 2.7.0"

env:
  - PUPPET_VERSION="2.7"
  - PUPPET_VERSION="3.0"
  - PUPPET_VERSION="3.1"
  - PUPPET_VERSION="3.2"

branches:
  only:
    - master
